service: serverless-plugin-node-shim-demo

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-plugin-node-shim

custom:
  nodeShim:
    execPath: node-v8.9.4-linux-x64/bin/node

package:
  excludeDevDependencies: false
  exclude:
    - "**/**"
  include:
    - node-v8.9.4-linux-x64/bin/node
    - src/**

functions:
  hello:
    handler: src/handler.hello
  world:
    handler: src/handler.world
  other:
    handler: src/other.other
